/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeBracket = { 'adult' : null } |
  { 'ages4To8' : null } |
  { 'ages13To17' : null } |
  { 'ages9To12' : null };
export type ChoreType = { 'cleaning' : null } |
  { 'misc' : null } |
  { 'homework' : null } |
  { 'outdoor' : null };
export interface QuestBrief {
  'id' : bigint,
  'missionText' : string,
  'encouragement' : string,
  'tips' : Array<string>,
}
export interface Reward {
  'id' : bigint,
  'cost' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'rewardType' : RewardType,
}
export interface RewardHistoryEntry {
  'redeemedBy' : bigint,
  'actionType' : { 'questCompleted' : null } |
    { 'rewardBought' : null },
  'rewardId' : bigint,
}
export type RewardType = { 'money' : null } |
  { 'gems' : null } |
  { 'points' : null };
export interface SystemSettings {
  'theme' : string,
  'rewardSystem' : RewardType,
}
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : [] | [bigint],
  'description' : string,
  'choreType' : ChoreType,
  'points' : bigint,
}
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'id' : bigint,
  'name' : string,
  'role' : UserRole,
  'worldTheme' : string,
  'avatarId' : string,
  'ageBracket' : AgeBracket,
  'points' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorldTheme { 'sceneStyling' : string, 'name' : string }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'becomeFirstAdmin' : ActorMethod<[], undefined>,
  'claimTask' : ActorMethod<[bigint], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'createReward' : ActorMethod<[string, bigint, RewardType], bigint>,
  'createTask' : ActorMethod<[string, string, ChoreType, bigint], bigint>,
  'generateQuest' : ActorMethod<
    [string, bigint, AgeBracket, string],
    QuestBrief
  >,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAvailableRewards' : ActorMethod<[], Array<Reward>>,
  'getAvailableWorldThemes' : ActorMethod<[], Array<WorldTheme>>,
  'getCallerProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderBoard' : ActorMethod<[], Array<UserProfile>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getRewardHistory' : ActorMethod<[bigint], Array<RewardHistoryEntry>>,
  'getSystemSettings' : ActorMethod<[], [] | [SystemSettings]>,
  'getTasks' : ActorMethod<[bigint], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redeemReward' : ActorMethod<[bigint], undefined>,
  'registerProfile' : ActorMethod<
    [string, UserRole, string, AgeBracket, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSystemSettings' : ActorMethod<[SystemSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];