/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RewardType = IDL.Variant({
  'money' : IDL.Null,
  'gems' : IDL.Null,
  'points' : IDL.Null,
});
export const ChoreType = IDL.Variant({
  'cleaning' : IDL.Null,
  'misc' : IDL.Null,
  'homework' : IDL.Null,
  'outdoor' : IDL.Null,
});
export const AgeBracket = IDL.Variant({
  'adult' : IDL.Null,
  'ages4To8' : IDL.Null,
  'ages13To17' : IDL.Null,
  'ages9To12' : IDL.Null,
});
export const QuestBrief = IDL.Record({
  'id' : IDL.Nat,
  'missionText' : IDL.Text,
  'encouragement' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'worldTheme' : IDL.Text,
  'avatarId' : IDL.Text,
  'ageBracket' : AgeBracket,
  'points' : IDL.Nat,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'choreType' : ChoreType,
  'points' : IDL.Nat,
});
export const Reward = IDL.Record({
  'id' : IDL.Nat,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'rewardType' : RewardType,
});
export const WorldTheme = IDL.Record({
  'sceneStyling' : IDL.Text,
  'name' : IDL.Text,
});
export const RewardHistoryEntry = IDL.Record({
  'redeemedBy' : IDL.Nat,
  'actionType' : IDL.Variant({
    'questCompleted' : IDL.Null,
    'rewardBought' : IDL.Null,
  }),
  'rewardId' : IDL.Nat,
});
export const SystemSettings = IDL.Record({
  'theme' : IDL.Text,
  'rewardSystem' : RewardType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'becomeFirstAdmin' : IDL.Func([], [], []),
  'claimTask' : IDL.Func([IDL.Nat], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'createReward' : IDL.Func([IDL.Text, IDL.Nat, RewardType], [IDL.Nat], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, ChoreType, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'generateQuest' : IDL.Func(
      [IDL.Text, IDL.Nat, AgeBracket, IDL.Text],
      [QuestBrief],
      [],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAvailableRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
  'getAvailableWorldThemes' : IDL.Func([], [IDL.Vec(WorldTheme)], ['query']),
  'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderBoard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getRewardHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(RewardHistoryEntry)],
      ['query'],
    ),
  'getSystemSettings' : IDL.Func([], [IDL.Opt(SystemSettings)], ['query']),
  'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redeemReward' : IDL.Func([IDL.Nat], [], []),
  'registerProfile' : IDL.Func(
      [IDL.Text, UserRole, IDL.Text, AgeBracket, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSystemSettings' : IDL.Func([SystemSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RewardType = IDL.Variant({
    'money' : IDL.Null,
    'gems' : IDL.Null,
    'points' : IDL.Null,
  });
  const ChoreType = IDL.Variant({
    'cleaning' : IDL.Null,
    'misc' : IDL.Null,
    'homework' : IDL.Null,
    'outdoor' : IDL.Null,
  });
  const AgeBracket = IDL.Variant({
    'adult' : IDL.Null,
    'ages4To8' : IDL.Null,
    'ages13To17' : IDL.Null,
    'ages9To12' : IDL.Null,
  });
  const QuestBrief = IDL.Record({
    'id' : IDL.Nat,
    'missionText' : IDL.Text,
    'encouragement' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'worldTheme' : IDL.Text,
    'avatarId' : IDL.Text,
    'ageBracket' : AgeBracket,
    'points' : IDL.Nat,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'choreType' : ChoreType,
    'points' : IDL.Nat,
  });
  const Reward = IDL.Record({
    'id' : IDL.Nat,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'rewardType' : RewardType,
  });
  const WorldTheme = IDL.Record({
    'sceneStyling' : IDL.Text,
    'name' : IDL.Text,
  });
  const RewardHistoryEntry = IDL.Record({
    'redeemedBy' : IDL.Nat,
    'actionType' : IDL.Variant({
      'questCompleted' : IDL.Null,
      'rewardBought' : IDL.Null,
    }),
    'rewardId' : IDL.Nat,
  });
  const SystemSettings = IDL.Record({
    'theme' : IDL.Text,
    'rewardSystem' : RewardType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'becomeFirstAdmin' : IDL.Func([], [], []),
    'claimTask' : IDL.Func([IDL.Nat], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'createReward' : IDL.Func([IDL.Text, IDL.Nat, RewardType], [IDL.Nat], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, ChoreType, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'generateQuest' : IDL.Func(
        [IDL.Text, IDL.Nat, AgeBracket, IDL.Text],
        [QuestBrief],
        [],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAvailableRewards' : IDL.Func([], [IDL.Vec(Reward)], ['query']),
    'getAvailableWorldThemes' : IDL.Func([], [IDL.Vec(WorldTheme)], ['query']),
    'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderBoard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getRewardHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(RewardHistoryEntry)],
        ['query'],
      ),
    'getSystemSettings' : IDL.Func([], [IDL.Opt(SystemSettings)], ['query']),
    'getTasks' : IDL.Func([IDL.Nat], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redeemReward' : IDL.Func([IDL.Nat], [], []),
    'registerProfile' : IDL.Func(
        [IDL.Text, UserRole, IDL.Text, AgeBracket, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSystemSettings' : IDL.Func([SystemSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };