/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SystemSettings {
    theme: string;
    rewardSystem: RewardType;
}
export interface Reward {
    id: bigint;
    cost: bigint;
    name: string;
    isAvailable: boolean;
    rewardType: RewardType;
}
export interface QuestBrief {
    id: bigint;
    missionText: string;
    encouragement: string;
    tips: Array<string>;
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    title: string;
    assignedTo?: bigint;
    description: string;
    choreType: ChoreType;
    points: bigint;
}
export interface WorldTheme {
    sceneStyling: string;
    name: string;
}
export interface RewardHistoryEntry {
    redeemedBy: bigint;
    actionType: Variant_questCompleted_rewardBought;
    rewardId: bigint;
}
export interface UserProfile {
    id: bigint;
    name: string;
    role: UserRole;
    worldTheme: string;
    avatarId: string;
    ageBracket: AgeBracket;
    points: bigint;
}
export enum AgeBracket {
    adult = "adult",
    ages4To8 = "ages4To8",
    ages13To17 = "ages13To17",
    ages9To12 = "ages9To12"
}
export enum ChoreType {
    cleaning = "cleaning",
    misc = "misc",
    homework = "homework",
    outdoor = "outdoor"
}
export enum RewardType {
    money = "money",
    gems = "gems",
    points = "points"
}
export enum TaskStatus {
    done = "done",
    todo = "todo",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_questCompleted_rewardBought {
    questCompleted = "questCompleted",
    rewardBought = "rewardBought"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    becomeFirstAdmin(): Promise<void>;
    claimTask(taskId: bigint): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    createReward(name: string, cost: bigint, rewardType: RewardType): Promise<bigint>;
    createTask(title: string, description: string, choreType: ChoreType, points: bigint): Promise<bigint>;
    generateQuest(questType: string, taskId: bigint, ageBracket: AgeBracket, theme: string): Promise<QuestBrief>;
    getAllProfiles(): Promise<Array<UserProfile>>;
    getAllTasks(): Promise<Array<Task>>;
    getAvailableRewards(): Promise<Array<Reward>>;
    getAvailableWorldThemes(): Promise<Array<WorldTheme>>;
    getCallerProfile(): Promise<UserProfile>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderBoard(): Promise<Array<UserProfile>>;
    getProfile(user: Principal): Promise<UserProfile>;
    getRewardHistory(callerProfileId: bigint): Promise<Array<RewardHistoryEntry>>;
    getSystemSettings(): Promise<SystemSettings | null>;
    getTasks(callerProfileId: bigint): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    redeemReward(rewardId: bigint): Promise<void>;
    registerProfile(name: string, role: UserRole, avatarId: string, ageBracket: AgeBracket, worldTheme: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setSystemSettings(settings: SystemSettings): Promise<void>;
}
import type { AgeBracket as _AgeBracket, ChoreType as _ChoreType, Reward as _Reward, RewardHistoryEntry as _RewardHistoryEntry, RewardType as _RewardType, SystemSettings as _SystemSettings, Task as _Task, TaskStatus as _TaskStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async becomeFirstAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.becomeFirstAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.becomeFirstAdmin();
            return result;
        }
    }
    async claimTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimTask(arg0);
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async createReward(arg0: string, arg1: bigint, arg2: RewardType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReward(arg0, arg1, to_candid_RewardType_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReward(arg0, arg1, to_candid_RewardType_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: ChoreType, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, to_candid_ChoreType_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, to_candid_ChoreType_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async generateQuest(arg0: string, arg1: bigint, arg2: AgeBracket, arg3: string): Promise<QuestBrief> {
        if (this.processError) {
            try {
                const result = await this.actor.generateQuest(arg0, arg1, to_candid_AgeBracket_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateQuest(arg0, arg1, to_candid_AgeBracket_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableRewards(): Promise<Array<Reward>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableRewards();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableRewards();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableWorldThemes(): Promise<Array<WorldTheme>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableWorldThemes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableWorldThemes();
            return result;
        }
    }
    async getCallerProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderBoard(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderBoard();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderBoard();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_UserProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewardHistory(arg0: bigint): Promise<Array<RewardHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardHistory(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardHistory(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemSettings(): Promise<SystemSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemSettings();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemSettings();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(arg0: bigint): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async redeemReward(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemReward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemReward(arg0);
            return result;
        }
    }
    async registerProfile(arg0: string, arg1: UserRole, arg2: string, arg3: AgeBracket, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_AgeBracket_n7(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_AgeBracket_n7(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSystemSettings(arg0: SystemSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSystemSettings(to_candid_SystemSettings_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSystemSettings(to_candid_SystemSettings_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AgeBracket_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeBracket): AgeBracket {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ChoreType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChoreType): ChoreType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RewardHistoryEntry_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardHistoryEntry): RewardHistoryEntry {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_RewardType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RewardType): RewardType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Reward_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reward): Reward {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_SystemSettings_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemSettings): SystemSettings {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemSettings]): SystemSettings | null {
    return value.length === 0 ? null : from_candid_SystemSettings_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _UserRole;
    worldTheme: string;
    avatarId: string;
    ageBracket: _AgeBracket;
    points: bigint;
}): {
    id: bigint;
    name: string;
    role: UserRole;
    worldTheme: string;
    avatarId: string;
    ageBracket: AgeBracket;
    points: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        worldTheme: value.worldTheme,
        avatarId: value.avatarId,
        ageBracket: from_candid_AgeBracket_n14(_uploadFile, _downloadFile, value.ageBracket),
        points: value.points
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    title: string;
    assignedTo: [] | [bigint];
    description: string;
    choreType: _ChoreType;
    points: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    title: string;
    assignedTo?: bigint;
    description: string;
    choreType: ChoreType;
    points: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n19(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.assignedTo)),
        description: value.description,
        choreType: from_candid_ChoreType_n22(_uploadFile, _downloadFile, value.choreType),
        points: value.points
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    cost: bigint;
    name: string;
    isAvailable: boolean;
    rewardType: _RewardType;
}): {
    id: bigint;
    cost: bigint;
    name: string;
    isAvailable: boolean;
    rewardType: RewardType;
} {
    return {
        id: value.id,
        cost: value.cost,
        name: value.name,
        isAvailable: value.isAvailable,
        rewardType: from_candid_RewardType_n27(_uploadFile, _downloadFile, value.rewardType)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redeemedBy: bigint;
    actionType: {
        questCompleted: null;
    } | {
        rewardBought: null;
    };
    rewardId: bigint;
}): {
    redeemedBy: bigint;
    actionType: Variant_questCompleted_rewardBought;
    rewardId: bigint;
} {
    return {
        redeemedBy: value.redeemedBy,
        actionType: from_candid_variant_n33(_uploadFile, _downloadFile, value.actionType),
        rewardId: value.rewardId
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    rewardSystem: _RewardType;
}): {
    theme: string;
    rewardSystem: RewardType;
} {
    return {
        theme: value.theme,
        rewardSystem: from_candid_RewardType_n27(_uploadFile, _downloadFile, value.rewardSystem)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    adult: null;
} | {
    ages4To8: null;
} | {
    ages13To17: null;
} | {
    ages9To12: null;
}): AgeBracket {
    return "adult" in value ? AgeBracket.adult : "ages4To8" in value ? AgeBracket.ages4To8 : "ages13To17" in value ? AgeBracket.ages13To17 : "ages9To12" in value ? AgeBracket.ages9To12 : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    done: null;
} | {
    todo: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "done" in value ? TaskStatus.done : "todo" in value ? TaskStatus.todo : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cleaning: null;
} | {
    misc: null;
} | {
    homework: null;
} | {
    outdoor: null;
}): ChoreType {
    return "cleaning" in value ? ChoreType.cleaning : "misc" in value ? ChoreType.misc : "homework" in value ? ChoreType.homework : "outdoor" in value ? ChoreType.outdoor : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    money: null;
} | {
    gems: null;
} | {
    points: null;
}): RewardType {
    return "money" in value ? RewardType.money : "gems" in value ? RewardType.gems : "points" in value ? RewardType.points : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    questCompleted: null;
} | {
    rewardBought: null;
}): Variant_questCompleted_rewardBought {
    return "questCompleted" in value ? Variant_questCompleted_rewardBought.questCompleted : "rewardBought" in value ? Variant_questCompleted_rewardBought.rewardBought : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reward>): Array<Reward> {
    return value.map((x)=>from_candid_Reward_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RewardHistoryEntry>): Array<RewardHistoryEntry> {
    return value.map((x)=>from_candid_RewardHistoryEntry_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AgeBracket_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeBracket): _AgeBracket {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ChoreType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChoreType): _ChoreType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RewardType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewardType): _RewardType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SystemSettings_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SystemSettings): _SystemSettings {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: UserRole;
    worldTheme: string;
    avatarId: string;
    ageBracket: AgeBracket;
    points: bigint;
}): {
    id: bigint;
    name: string;
    role: _UserRole;
    worldTheme: string;
    avatarId: string;
    ageBracket: _AgeBracket;
    points: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_UserRole_n1(_uploadFile, _downloadFile, value.role),
        worldTheme: value.worldTheme,
        avatarId: value.avatarId,
        ageBracket: to_candid_AgeBracket_n7(_uploadFile, _downloadFile, value.ageBracket),
        points: value.points
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    theme: string;
    rewardSystem: RewardType;
}): {
    theme: string;
    rewardSystem: _RewardType;
} {
    return {
        theme: value.theme,
        rewardSystem: to_candid_RewardType_n3(_uploadFile, _downloadFile, value.rewardSystem)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RewardType): {
    money: null;
} | {
    gems: null;
} | {
    points: null;
} {
    return value == RewardType.money ? {
        money: null
    } : value == RewardType.gems ? {
        gems: null
    } : value == RewardType.points ? {
        points: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ChoreType): {
    cleaning: null;
} | {
    misc: null;
} | {
    homework: null;
} | {
    outdoor: null;
} {
    return value == ChoreType.cleaning ? {
        cleaning: null
    } : value == ChoreType.misc ? {
        misc: null
    } : value == ChoreType.homework ? {
        homework: null
    } : value == ChoreType.outdoor ? {
        outdoor: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeBracket): {
    adult: null;
} | {
    ages4To8: null;
} | {
    ages13To17: null;
} | {
    ages9To12: null;
} {
    return value == AgeBracket.adult ? {
        adult: null
    } : value == AgeBracket.ages4To8 ? {
        ages4To8: null
    } : value == AgeBracket.ages13To17 ? {
        ages13To17: null
    } : value == AgeBracket.ages9To12 ? {
        ages9To12: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
